function showInput() {
    var html = '';

    var city = document.getElementById("cityList").value;
    $("#eleInput").empty();

    var myobj = {};
    myobj["city"] = city;

    $.ajax({
        type: "POST",
        async: false,
        url: "php/viewAllCityData.php",
        contentType: "application/json",
        data: JSON.stringify(myobj),
        success: function (data) {
            var divList = JSON.parse(data);

            $.each(divList, function (index, element1) {
                var electricity = element1.electricity;
                var transport = element1.transport;

                var cropland = element1.cropland;
                var livestock = element1.livestock;
                var forest = element1.forest;
                var landuse = element1.landuse;

                var solidwaste = element1.solidwaste;
                var yard = element1.yard;

                var hazwaste = element1.hazwaste;
                var biomwaste = element1.biomwaste;

                var wastewater = element1.wastewater;
                var stp = element1.stp;

                var energyindu = element1.energyindu;

                var ppcement = element1.ppcement;
                var ppchemical = element1.ppchemical;

                var indu_other = element1.indu_other;

                var cooking = element1.cooking;

                $.each(electricity, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '    <div class="in-sec">'
                            + '        <h3 class="text-center mb-2"> Input Values of Electricity Sector</h3>'
                            + '        <table class="table text-center">'
                            + '           <thead>'
                            + '               <tr>'
                            + '                    <th scope="col">Sr.No</th>'
                            + '                    <th scope="col">Sub-Sector</th>'
                            + '                    <th scope="col">Electricity used(MW/m)</th>'
                            + '                </tr>'
                            + '            </thead>'
                            + '            <tbody>'
                            + '                <tr>'
                            + '                   <th scope="row">1</th>'
                            + '                    <td>Residential ELEC use</td>'
                            + '                    <td>12</td>'
                            + '                </tr>'
                            + '                <tr>'
                            + '                   <th scope="row">2</th>'
                            + '                   <td>Commercial ELEC use</td>'
                            + '                     <td>34</td>'
                            + '              </tr>'
                            + '               <tr>'
                            + '                 <th scope="row">3</th>'
                            + '                 <td>Slum area ELEC use</td>'
                            + '                 <td>65</td>'
                            + '         </tr>'
                            + '       <tr>'
                            + '           <th scope="row">4</th>'
                            + '           <td>Street light ELEC use</td>'
                            + '         <td>53</td>'
                            + '      </tr>'
                            + '    </tbody>'
                            + '     </table>'

                            + '  </div>'
                            + '   </div>'
                            + ' </div> ';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }

                });
                $.each(transport, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + ' <div class="in-sec">'
                            + '     <h3 class="text-center mb-2"> Input Values of Transport Sector</h3>'
                            + '    <table class="table text-center">'
                            + '       <thead>'
                            + '            <tr>'
                            + '                <th scope="col">Sr.No</th>'
                            + '                 <th scope="col">Type of Vehicle</th>'
                            + '                 <th scope="col">No. Of Vehicles</th>'
                            + '              </tr>'
                            + '         </thead>'
                            + '         <tbody>'
                            + '   <tr>'
                            + '                  <th scope="row">1</th>'
                            + '                   <td>Two Wheeler</td>'
                            + '    <td>12</td>'
                            + '   </tr>'
                            + '   <tr>'
                            + '      <th scope="row">2</th>'
                            + '     <td>Three Wheeler</td>'
                            + '     <td>34</td>'
                            + '   </tr>'
                            + '  <tr>'
                            + '     <th scope="row">3</th>'
                            + '    <td>Four Wheeler</td>'
                            + '   <td>65</td>'
                            + '  </tr>'
                            + '  <tr>'
                            + '      <th scope="row">4</th>'
                            + '      <td>Bus</td>'
                            + '     <td>53</td>'
                            + '  </tr>'
                            + '  <tr>'
                            + '   <th scope="row">5</th>'
                            + '   <td>LCV</td>'
                            + '   <td>53</td>'
                            + '  </tr>'
                            + '  <tr>'
                            + '     <th scope="row">6</th>'
                            + '     <td>HCV</td>'
                            + '     <td>53</td>'
                            + '   </tr>'
                            + '  <tr>'
                            + '       <th scope="row">7</th>'
                            + '       <td>Train</td>'
                            + '      <td>53</td>'
                            + '   </tr>'
                            + '   <tr>'
                            + '      <th scope="row">8</th>'
                            + '      <td>Flight</td>'
                            + '       <td>53</td>'
                            + '   </tr>'
                            + '  </tbody>'
                            + ' </table>'

                            + '  </div>'
                            + '   </div>'
                            + ' </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(cropland, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Input Values of Crop Land Sector</h3>'
                            + '      <table class="table text-center">'
                            + '           <thead>'
                            + '               <tr>'
                            + '                   <th scope="col">Sr.No</th>'
                            + '                   <th scope="col">Input</th>'
                            + '                   <th scope="col">Area(sq.km)</th>'
                            + '              </tr>'
                            + '          </thead>'
                            + '          <tbody>'
                            + '              <tr>'
                            + '                     <th scope="row">1</th>'
                            + '                    <td>Area Occupied by Agricultural Land</td>'
                            + '                    <td>122</td>'
                            + '                 </tr>'
                            + '             </tbody>'
                            + '         </table>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(livestock, function (index, element) {
                    if (element.check == "true") {
                        html += ' <div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '     <h3 class="text-center mb-2"> Input Values of Livestock Sector</h3>'
                            + '    <table class="table text-center">'
                            + '        <thead>'
                            + '            <tr>'
                            + '               <th scope="col">Sr.No</th>'
                            + '               <th scope="col"> Type of Animal</th>'
                            + '               <th scope="col"> Number of Animals</th>'
                            + '           </tr>'
                            + '        </thead>'
                            + '        <tbody>'
                            + '           <tr>'
                            + '              <th scope="row">1</th>'
                            + '             <td>Indigenous Cattles</td>'
                            + '           <td>122</td>'
                            + '        </tr>'
                            + '        <tr>'
                            + '            <th scope="row">2</th>'
                            + '           <td>Cross-breed cattles</td>'
                            + '           <td>122</td>'
                            + '       </tr>'
                            + '       <tr>'
                            + '           <th scope="row">3</th>'
                            + '           <td>Buffalo</td>'
                            + '           <td>122</td>'
                            + '          </tr>'
                            + '         <tr>'
                            + '             <th scope="row">4</th>'
                            + '            <td>Sheep</td>'
                            + '              <td>122</td>'
                            + '          </tr>'
                            + '          <tr>'
                            + '            <th scope="row">5</th>'
                            + '           <td>Goat</td>'
                            + '           <td>122</td>'
                            + '      </tr>'
                            + '     <tr>'
                            + '   <th scope="row">6</th>'
                            + '   <td>Horses</td>'
                            + '   <td>122</td>'
                            + '  </tr>'
                            + ' <tr>'
                            + '       <th scope="row">7</th>'
                            + '        <td>Donkeys</td>'
                            + '        <td>122</td>'
                            + '    </tr>'
                            + '    <tr>'
                            + '        <th scope="row">8</th>'
                            + '       <td>Camels</td>'
                            + '       <td>122</td>'
                            + '    </tr>'
                            + '      <tr>'
                            + '       <th scope="row">9</th>'
                            + '      <td>Pig</td>'
                            + '      <td>122</td>'
                            + '   </tr>'
                            + '  <tr>'
                            + '     <th scope="row">10</th>'
                            + '     <td>Poultry</td>'
                            + '    <td>122</td>'
                            + '  </tr>'
                            + '  </tbody>'
                            + '  </table>'

                            + ' </div>'
                            + '  </div>'
                            + '   </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(forest, function (index, element) {
                    if (element.check == "true") {
                        html + '<div class="row  align-items-center justify-content-center mt-3">'
                            + '   <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '     <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Input Values of Forest Land Sector</h3>'
                            + '      <table class="table text-center">'
                            + '          <thead>'
                            + '             <tr>'
                            + '                 <th scope="col">Sr.No</th>'
                            + '                 <th scope="col">Input</th>'
                            + '                <th scope="col">Area(sq.km)</th>'
                            + '           </tr>'
                            + '       </thead>'
                            + '      <tbody>'
                            + '          <tr>'
                            + '              <th scope="row">1</th>'
                            + '               <td>Area under Forest Land</td>'
                            + '               <td>122</td>'
                            + '            </tr>'
                            + '        </tbody>'
                            + '     </table>'
                            + '    </div>'
                            + '    </div>'
                            + '   </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(landuse, function (index, element) {
                    if (element.check == "true") {
                        html += '  <div class="row  align-items-center justify-content-center mt-3">'
                            + '  <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '     <div class="in-sec">'
                            + '       <h3 class="text-center mb-2"> Input Values of Land Use Sector</h3>'
                            + '      <table class="table text-center">'
                            + '         <thead>'
                            + '            <tr>'
                            + '              <th scope="col">Sr.No</th>'
                            + '              <th scope="col">Category</th>'
                            + '              <th scope="col">Area(sq.km)</th>'
                            + '        </tr>'
                            + '   </thead>'
                            + '  <tbody>'
                            + '       <tr>'
                            + '           <th scope="row">1</th>'
                            + '            <td>Residential Area</td>'
                            + '           <td>122</td>'
                            + '      </tr>'
                            + '      <tr>'
                            + '         <th scope="row">2</th>'
                            + '       <td>Commercial Area</td>'
                            + '      <td>122</td>'
                            + '  </tr>'
                            + '   <tr>'
                            + '      <th scope="row">3</th>'
                            + '     <td>Water Bodies Area</td>'
                            + '    <td>122</td>'
                            + '  </tr>'
                            + '    <tr>'
                            + '        <th scope="row">4</th>'
                            + '        <td>Public</td>'
                            + '      <td>122</td>'
                            + '    </tr>'
                            + '   <tr>'
                            + '      <th scope="row">5</th>'
                            + '      <td>Public Utilities Area</td>'
                            + '     <td>122</td>'
                            + '   </tr>'
                            + '    <tr>'
                            + '       <th scope="row">6</th>'
                            + '      <td>Transport</td>'
                            + '     <td>122</td>'
                            + '    </tr>'
                            + ' <tr>'
                            + '     <th scope="row">7</th>'
                            + '    <td>Green Area</td>'
                            + '   <td>122</td>'
                            + '  </tr>'
                            + '    <tr>'
                            + '       <th scope="row">8</th>'
                            + '      <td>Recreational Area</td>'
                            + '     <td>122</td>'
                            + '    </tr>'
                            + '  <tr>'
                            + '     <th scope="row">9</th>'
                            + '    <td>Industrial Area</td>'
                            + '   <td>122</td>'
                            + '  </tr>'
                            + '      <tr>'
                            + '        <th scope="row">10</th>'
                            + '         <td>Hills and Hill Slopes Area</td>'
                            + '      <td>122</td>'
                            + '    </tr>'

                            + ' </tbody>'
                            + '  </table>'
                            + '  </div>'
                            + ' </div>'
                            + '  </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(solidwaste, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '   <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '      <div class="in-sec">'
                            + '        <h3 class="text-center mb-2"> Input Values of Municipal Solid Waste Sector</h3>'
                            + '      <table class="table text-center">'
                            + '          <thead>'
                            + '             <tr>'
                            + '                 <th scope="col">Sr.No</th>'
                            + '                 <th scope="col">Input</th>'
                            + '                 <th scope="col">Quantity</th>'
                            + '             </tr>'
                            + '        </thead>'
                            + '        <tbody>'
                            + '            <tr>'
                            + '                <th scope="row">1</th>'
                            + '                 <td> Solid Waste Generated(MTD)</td>'
                            + '                 <td>122</td>'
                            + '             </tr>'
                            + '             <tr>'
                            + '               <th scope="row">1</th>'
                            + '               <td> Solid Waste Collected(MTD)</td>'
                            + '              <td>122</td>'
                            + '          </tr>'
                            + '          <tr>'
                            + '                   <th scope="row">1</th>'
                            + '                  <td> Solid Waste Treated(MTD)</td>'
                            + '                   <td>122</td>'
                            + '             </tr>'
                            + '             <tr>'
                            + '                 <th scope="row">1</th>'
                            + '                 <td> No. of Dumping Yards </td>'
                            + '                 <td>2</td>'
                            + '               </tr>'
                            + '            </tbody>'
                            + '        </table>'
                            + '     </div>'
                            + '   </div>'
                            + ' </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(yard, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '   <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '      <div class="in-sec">'
                            + '       <h3 class="text-center mb-2"> Input Values of Dumping Yards</h3>'
                            + '      <table class="table text-center">'
                            + '          <thead>'
                            + '             <tr>'
                            + '                <th scope="col">Sr.No.</th>'
                            + '                <th scope="col">Area of Dumping Yard</th>'
                            + '               <th scope="col">Latitude</th>'
                            + '               <th scope="col">Logitude</th>'
                            + '               <th scope="col">Approximate Waste</th>'
                            + '            </tr>'
                            + '        </thead>'
                            + '        <tbody>'
                            + '           <tr>'
                            + '              <th scope="row">1</th>'
                            + '              <td>122</td>'
                            + '             <td>122</td>'
                            + '             <td>122</td>'
                            + '            <td>122</td>'
                            + '       </tr>'
                            + '      <tr>'
                            + '         <th scope="row">2</th>'
                            + '         <td>122</td>'
                            + '         <td>122</td>'
                            + '         <td>122</td>'
                            + '         <td>122</td>'
                            + '       </tr>'
                            + '      </tbody>'
                            + '   </table>'
                            + '   </div>'
                            + '   </div>'
                            + '   </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(biomwaste, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '   <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '       <div class="in-sec">'
                            + '          <h3 class="text-center mb-2"> Input Values of Biomedical Waste Sector</h3>'
                            + '        <table class="table text-center">'
                            + '            <thead>'
                            + '                <tr>'
                            + '                   <th scope="col">Sr.No</th>'
                            + '                 <th scope="col">Input</th>'
                            + '                 <th scope="col">Amount(MTD)</th>'
                            + '              </tr>'
                            + '           </thead>'
                            + '          <tbody>'
                            + '               <tr>'
                            + '                   <th scope="row">1</th>'
                            + '                    <td> Biomedical Waste Generated</td>'
                            + '                   <td>122</td>'
                            + '               </tr>'
                            + '               <tr>'
                            + '                  <th scope="row">2</th>'
                            + '                  <td> Biomedical Waste Collected</td>'
                            + '                 <td>122</td>'
                            + '              </tr>'
                            + '              <tr>'
                            + '                  <th scope="row">3</th>'
                            + '                    <td> Biomedical Waste Treated</td>'
                            + '                    <td>122</td>'
                            + '                  </tr>'
                            + '              </tbody>'
                            + '        </table>'
                            + '      </div>'
                            + '     </div>'
                            + '     </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(hazwaste, function (index, element) {
                    if (element.check == "true") {
                        html += '     <div class="row  align-items-center justify-content-center mt-3">'
                            + '      <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '      <div class="in-sec">'
                            + '        <h3 class="text-center mb-2"> Input Values of Hazardous Waste Sector</h3>'
                            + '     <table class="table text-center">'
                            + '         <thead>'
                            + '                 <tr>'
                            + '                     <th scope="col">Sr.No.</th>'
                            + '                    <th scope="col">Input</th>'
                            + '                    <th scope="col">Amount(MTD)</th>'
                            + '                </tr>'
                            + '            </thead>'
                            + '             <tbody>'
                            + '                 <tr>'
                            + '                     <th scope="row">1</th>'
                            + '                     <td>Generated Quantity of Hazardous Waste</td>'
                            + '                     <td>122</td>'
                            + '                 </tr>'
                            + '                 <tr>'
                            + '                     <th scope="row">2</th>'
                            + '                     <td>Collected Quantity of Hazardous Waste</td>'
                            + '                    <td>122</td>'
                            + '                </tr>'
                            + '                 <tr>'
                            + '                     <th scope="row">3</th>'
                            + '                     <td>Treated Quantity of Hazardous Waste</td>'
                            + '                     <td>122</td>'
                            + '                 </tr>'
                            + '              </tbody>'
                            + '         </table>'
                            + '      </div>'
                            + '   </div>'
                            + '  </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(wastewater, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '    <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '   <div class="in-sec">'
                            + '     <h3 class="text-center mb-2"> Input Values of Wastewater Sector</h3>'
                            + '    <table class="table text-center">'
                            + '        <thead>'
                            + '          <tr>'
                            + '             <th scope="col">Sr.No</th>'
                            + '             <th scope="col">input</th>'
                            + '             <th scope="col">Value</th>'
                            + '        </tr>'
                            + '     </thead>'
                            + '     <tbody>'
                            + '         <tr>'
                            + '             <th scope="row">1</th>'
                            + '         <td>Water Consumption(CMD)</td>'
                            + '         <td>122</td>'
                            + '     </tr>'
                            + '     <tr>'
                            + '         <th scope="row">2</th>'
                            + '         <td>Wastewater Generated(CMD)</td>'
                            + '        <td>122</td>'
                            + '     </tr>'
                            + '     <tr>'
                            + '        <th scope="row">3</th>'
                            + '        <td>Waste water Collection(CMD)</td>'
                            + '        <td>122</td>'
                            + '    </tr>'
                            + '      <tr>'
                            + '        <th scope="row">4</th>'
                            + '       <td>Qty of treat waste water</td>'
                            + '       <td>122</td>'
                            + '     </tr>'
                            + '    <tr>'
                            + '        <th scope="row">5</th>'
                            + '       <td>No of STP</td>'
                            + '        <td>5</td>'
                            + '     </tr>'
                            + '    </tbody>'
                            + '    </table>'
                            + '   </div>'
                            + '   </div>'
                            + '     </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(stp, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '   <div class="col-md-8 col-lg-8 mb-3" data-aos-delay="200">'
                            + '    <div class="in-sec">'
                            + '        <h3 class="text-center mb-2"> Input Values of STP</h3>'
                            + '       <table class="table text-center">'
                            + '          <thead>'
                            + '             <tr>'
                            + '                <th scope="col">STP No.</th>'
                            + '               <th scope="col">Capacity</th>'
                            + '                <th scope="col">Latitude</th>'
                            + '               <th scope="col">Logitude</th>'
                            + '               <th scope="col">Technology</th>'
                            + '              <th scope="col">Recycling Water</th>'
                            + '              <th scope="col">Disposal of Waste</th>'
                            + '         </tr>'
                            + '      </thead>'
                            + '      <tbody>'
                            + '          <tr>'
                            + '              <th scope="row">1</th>'
                            + '              <td>122</td>'
                            + '              <td>122</td>'
                            + '              <td>122</td>'
                            + '              <td>122</td>'
                            + '              <td>122</td>'
                            + '           <td>122</td>'
                            + '       </tr>'
                            + '       <tr>'
                            + '    <th scope="row">2</th>'
                            + '    <td>122</td>'
                            + '    <td>122</td>'
                            + '   <td>122</td>'
                            + '  <td>122</td>'
                            + '   <td>122</td>'
                            + '   <td>122</td>'
                            + '   </tr>'
                            + '   <tr>'
                            + '      <th scope="row">3</th>'
                            + '   <td>122</td>'
                            + '   <td>122</td>'
                            + '   <td>122</td>'
                            + '  <td>122</td>'
                            + '   <td>122</td>'
                            + '   <td>122</td>'
                            + '    </tr>'
                            + '  <tr>'
                            + '     <th scope="row">4</th>'
                            + '    <td>122</td>'
                            + '   <td>122</td>'
                            + '  <td>122</td>'
                            + ' <td>122</td>'
                            + '  <td>122</td>'
                            + '  <td>122</td>'
                            + ' </tr>'
                            + '  <tr>'
                            + '    <th scope="row">5</th>'
                            + '   <td>122</td>'
                            + '  <td>122</td>'
                            + '  <td>122</td>'
                            + '  <td>122</td>'
                            + '  <td>122</td>'
                            + '   <td>122</td>'
                            + '   </tr>'
                            + '   </tbody>'
                            + '   </table>'
                            + '  </div>'
                            + '   </div>'
                            + '  </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(energyindu, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '     <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '<div class="in-sec">'
                            + '    <h3 class="text-center mb-2"> Input Values of Industrial Energy Use Sector</h3>'
                            + '    <table class="table text-center">'
                            + '        <thead>'
                            + '            <tr>'
                            + '                 <th scope="col">Sr.No</th>'
                            + '                  <th scope="col">Fuel Type</th>'
                            + '                  <th scope="col">Amount(MTD)</th>'
                            + '               </tr>'
                            + '            </thead>'
                            + '             <tbody>'
                            + '                 <tr>'
                            + '                     <th scope="row">1</th>'
                            + '                     <td>Coal</td>'
                            + '                     <td>122</td>'
                            + '               </tr>'
                            + '                <tr>'
                            + '                    <th scope="row">2</th>'
                            + '                     <td>FO</td>'
                            + '                      <td>122</td>'
                            + '                  </tr>'
                            + '                  <tr>'
                            + '                     <th scope="row">3</th>'
                            + '                       <td>LDO</td>'
                            + '                      <td>122</td>'
                            + '                  </tr>'
                            + '                  <tr>'
                            + '                      <th scope="row">4</th>'
                            + '                      <td>HSD</td>'
                            + '                      <td>122</td>'
                            + '                  </tr>'
                            + '                  <tr>'
                            + '                      <th scope="row">5</th>'
                            + '                      <td>PNG</td>'
                            + '                      <td>122</td>'
                            + '                  </tr>'
                            + '                  <tr>'
                            + '                      <th scope="row">6</th>'
                            + '                     <td>NG</td>'
                            + '                       <td>122</td>'
                            + '                   </tr>'
                            + '                   <tr>'
                            + '                      <th scope="row">7</th>'
                            + '                     <td>Briquette</td>'
                            + '                       <td>122</td>'
                            + '                  </tr>'
                            + '                  <tr>'
                            + '                       <th scope="row">8</th>'
                            + '                       <td>Wood</td>'
                            + '                      <td>122</td>'
                            + '                  </tr>'
                            + '              </tbody>'
                            + '           </table>'

                            + '       </div>'
                            + '    </div>'
                            + ' </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(ppcement, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '     <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '       <div class="in-sec">'
                            + '          <h3 class="text-center mb-2"> Input Values of Industrial Process and Product (Cement) Sector</h3>'
                            + '         <table class="table text-center">'
                            + '               <thead>'
                            + '                  <tr>'
                            + '                      <th scope="col">Sr.No</th>'
                            + '                      <th scope="col">Cement Type</th>'
                            + '                      <th scope="col">Amount(tons/year)</th>'
                            + '                  </tr>'
                            + '              </thead>'
                            + '              <tbody>'
                            + '                  <tr>'
                            + '                       <th scope="row">1</th>'
                            + '                       <td>O.P.C.</td>'
                            + '                      <td>122</td>'
                            + '                  </tr>'
                            + '                  <tr>'
                            + '                       <th scope="row">2</th>'
                            + '                      <td>P.P.C.</td>'
                            + '                  <td>122</td>'
                            + '                </tr>'
                            + '               <tr>'
                            + '                  <th scope="row">3</th>'
                            + '                  <td>P.B.F.S.</td>'
                            + '                  <td>122</td>'
                            + '              </tr>'
                            + '              <tr>'
                            + '                  <th scope="row">4</th>'
                            + '                <td>S.R.C.</td>'
                            + '               <td>122</td>'
                            + '           </tr>'
                            + '           <tr>'
                            + '               <th scope="row">5</th>'
                            + '                <td>I.R.S.T.40</td>'
                            + '               <td>122</td>'
                            + '            </tr>'
                            + '         </tbody>'
                            + '        </table>'

                            + '      </div>'
                            + '    </div>'
                            + '  </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(ppchemical, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '    <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '     <div class="in-sec">'
                            + '        <h3 class="text-center mb-2"> Input Values of Industrial Process and Product (Chemical) Sector</h3>'
                            + '        <table class="table text-center">'
                            + '          <thead>'
                            + '              <tr>'
                            + '                  <th scope="col">Sr.No</th>'
                            + '              <th scope="col">Chemical type</th>'
                            + '             <th scope="col">Amount(tons/year)</th>'
                            + '          </tr>'
                            + '      </thead>'
                            + '     <tbody>'
                            + '      <tr>'
                            + '            <th scope="row">1</th>'
                            + '            <td>Ammonia</td>'
                            + '           <td>122</td>'
                            + '       </tr>'
                            + '       <tr>'
                            + '            <th scope="row">2</th>'
                            + '            <td>Inorganic Acids</td>'
                            + '            <td>122</td>'
                            + '        </tr>'
                            + '        <tr>'
                            + '            <th scope="row">3</th>'
                            + '            <td>Amides</td>'
                            + '            <td>122</td>'
                            + '        </tr>'
                            + '        <tr>'
                            + '          <th scope="row">4</th>'
                            + '         <td>Aldehydes</td>'
                            + '        <td>122</td>'
                            + '      </tr>'
                            + '    <tr>'
                            + '        <th scope="row">5</th>'
                            + '       <td>Organic Acids</td>'
                            + '      <td>122</td>'
                            + '   </tr>'
                            + '   <tr>'
                            + '       <th scope="row">6</th>'
                            + '       <td>Carbides</td>'
                            + '     <td>122</td>'
                            + '   </tr>'
                            + '   <tr>'
                            + '     <th scope="row">7</th>'
                            + '    <td>Soda Ash</td>'
                            + '    <td>122</td>'
                            + '    </tr>'
                            + '   <tr>'
                            + '        <th scope="row">8</th>'
                            + '      <td>Alcohols</td>'
                            + '     <td>122</td>'
                            + '    </tr>'
                            + '   <tr>'
                            + '       <th scope="row">9</th>'
                            + '      <td>Alkenes</td>'
                            + '      <td>122</td>'
                            + '   </tr>'
                            + '  <tr>'
                            + '     <th scope="row">10</th>'
                            + '     <td>Organochlorides</td>'
                            + '     <td>122</td>'
                            + '   </tr>'
                            + '      <tr>'
                            + '        <th scope="row">11</th>'
                            + '       <td>Oxide Compounds</td>'
                            + '      <td>122</td>'
                            + '    </tr>'
                            + '   <tr>'
                            + '      <th scope="row">12</th>'
                            + '     <td>Cyanide Compounds</td>'
                            + '     <td>122</td>'
                            + '     </tr>'
                            + '   <tr>'
                            + '    <th scope="row">13</th>'
                            + '    <td>Carbon Black</td>'
                            + '    <td>122</td>'
                            + '   </tr>'
                            + '   </tbody>'
                            + '    </table>'
                            + '   </div>'
                            + '   </div>'
                            + '  </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(indu_other, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '    <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '   <div class="in-sec">'
                            + '       <h3 class="text-center mb-2"> Input Values of Industrial Process and Product (Aluminium) Sector</h3>'
                            + '      <table class="table text-center">'
                            + '          <thead>'
                            + '             <tr>'
                            + '                <th scope="col">Sr.No</th>'
                            + '               <th scope="col">Input</th>'
                            + '              <th scope="col">Amount(tons/year)</th>'
                            + '         </tr>'
                            + '     </thead>'
                            + '   <tbody>'
                            + '      <tr>'
                            + '          <th scope="row">1</th>'
                            + '          <td>Aluminium</td>'
                            + '         <td>122</td>'
                            + '        </tr>'
                            + '     </tbody>'
                            + '     </table>'
                            + '   </div>'
                            + '   </div>'
                            + '     </div>';
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '   <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '   <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Input Values of Industrial Process and Product (Lead) Sector</h3>'
                            + '       <table class="table  text-center">'
                            + '       <thead>'
                            + '          <tr>'
                            + '             <th scope="col">Sr.No</th>'
                            + '           <th scope="col">Input</th>'
                            + '            <th scope="col">Amount(tons/year)</th>'
                            + '       </tr>'
                            + '   </thead>'
                            + '   <tbody>'
                            + '       <tr>'
                            + '           <th scope="row">1</th>'
                            + '           <td>Lead</td>'
                            + '           <td>122</td>'
                            + '       </tr>'
                            + '    </tbody>'
                            + '   </table>'
                            + '   </div>'
                            + '   </div>'
                            + ' </div>';
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '   <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '     <div class="in-sec">'
                            + '       <h3 class="text-center mb-2"> Input Values of Industrial Process and Product (Zinc) Sector</h3>'
                            + '        <table class="table text-center">'
                            + '           <thead>'
                            + '               <tr>'
                            + '                   <th scope="col">Sr.No</th>'
                            + '                   <th scope="col">Input</th>'
                            + '                  <th scope="col">Amount(tons/year)</th>'
                            + '              </tr>'
                            + '          </thead>'
                            + '           <tbody>'
                            + '              <tr>'
                            + '                <th scope="row">1</th>'
                            + '                <td>Zinc</td>'
                            + '                <td>122</td>'
                            + '             </tr>'
                            + '          </tbody>'
                            + '       </table>'
                            + '     </div>'
                            + '    </div>'
                            + '  </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });
                $.each(cooking, function (index, element) {
                    if (element.check == "true") {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + ' <div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '    <div class="in-sec">'
                            + '       <h3 class="text-center mb-2"> Input Values of Cooking Fuel Sector</h3>'
                            + '      <table class="table text-center">'
                            + '          <thead>'
                            + '              <tr>'
                            + '                  <th scope="col">Sr.No</th>'
                            + '                  <th scope="col">Cooking Fuel</th>'
                            + '                  <th scope="col">Amount</th>'
                            + '              </tr>'
                            + '          </thead>'
                            + '          <tbody>'
                            + '              <tr>'
                            + '                  <th scope="row">1</th>'
                            + '                   <td>Residential LPG</td>'
                            + '                   <td>122</td>'
                            + '               </tr>'
                            + '               <tr>'
                            + '                    <th scope="row">2</th>'
                            + '                  <td>Commercial LPG</td>'
                            + '                  <td>122</td>'
                            + '              </tr>'
                            + '              <tr>'
                            + '                   <th scope="row">3</th>'
                            + '                   <td>Residential MNGL</td>'
                            + '                   <td>122</td>'
                            + '              </tr>'
                            + '              <tr>'
                            + '                 <th scope="row">4</th>'
                            + '                 <td>Commercial MNGL</td>'
                            + '                <td>122</td>'
                            + '            </tr>'
                            + '           <tr>'
                            + '  <th scope="row">5</th>'
                            + '  <td>Residential Kerosene</td>'
                            + ' <td>122</td>'
                            + '  </tr>'
                            + '  <tr>'
                            + '      <th scope="row">6</th>'
                            + '     <td>Commercial Kerosene</td>'
                            + '    <td>122</td>'
                            + '  </tr>'
                            + '   <tr>'
                            + '     <th scope="row">7</th>'
                            + '     <td>Residential Wood</td>'
                            + '     <td>122</td>'
                            + ' </tr>'
                            + '   <tr>'
                            + '     <th scope="row">8</th>'
                            + '     <td>Commercial Wood</td>'
                            + '     <td>122</td>'
                            + '   </tr>'
                            + '  </tbody>'
                            + ' </table>'

                            + ' </div>'
                            + '   </div>'
                            + ' </div>';
                    }
                    else {
                        html += '<div class="row  align-items-center justify-content-center mt-3">'
                            + '<div class="col-md-6 col-lg-6 mb-3" data-aos-delay="200">'
                            + '  <div class="in-sec">'
                            + '      <h3 class="text-center mb-2"> Data NOT Found</h3>'
                            + '      </div>'
                            + '</div>'
                            + ' </div>';
                    }
                });

            });
        }
    });

    $("#sectorInfo").append(html);

}